compile : mManager.cpp Manager.cpp ../Reader/Reader.cpp ../Equation/Equation.cpp ../Equation/Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp ../Saver/Saver.cpp ../Logger/Logger.cpp ../Logger/Log.cpp
  g++ mManager.cpp Manager.cpp ../Reader/Reader.cpp ../Equation/Equation.cpp ../Equation/Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp ../Saver/Saver.cpp ../Logger/Logger.cpp ../Logger/Log.cpp -o e
run : e.exe
  e.exe