compile : mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp
  g++ mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp -o e
run : e.exe
  e.exe