compile : mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Token/Number.cpp ../Token/NumberArab.cpp ../Token/NumberRomawi.cpp ../Extension/Extension.cpp ../Token/Logic.cpp EquationException.cpp
  g++ mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Token/Number.cpp ../Token/NumberArab.cpp ../Token/NumberRomawi.cpp ../Extension/Extension.cpp ../Token/Logic.cpp EquationException.cpp -o e
run : e.exe
  e.exe