compile : mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp
  g++ mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp -o e
run : e.exe
  e.exe