compile : mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp ../Logic/Logic.cpp ../EquationException/EquationException.cpp
  g++ mEquation.cpp Equation.cpp Expression.cpp ../Token/Token.cpp ../Number/NumberArab.cpp ../Number/NumberRomawi.cpp ../Extension/Extension.cpp ../Logic/Logic.cpp ../EquationException/EquationException.cpp -o e
run : e.exe
  e.exe